# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_update_small_home

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17-23/1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_update_small_home
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【更新东东小窝信息】'
        run: |
          node jd_update_home.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      - name: '运行 【更新818互助码】'
        run: |
          node updateShareCode.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
        
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update by lxk0301" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
      #- name: Purge CDN Cache
      #  run: curl https://purge.jsdelivr.net/gh/fickgit/updateTeam@master/jd_updateSmallHomeInviteCode.json
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: ${{ secrets.SRC_USER }}
          dst: ${{ secrets.DST_USER }}
          static_list: "updateTeam"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
